# Generated by Django 4.2.4 on 2023-08-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltandpepper_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=5)),
                ('priceL', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bImage', models.URLField()),
            ],
        ),
    ]
